// Code generated by protoc-gen-go. DO NOT EDIT.
// source: src/login.proto

package msg

import (
	fmt "fmt"
	math "math"

	proto "github.com/golang/protobuf/proto"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type LoginFaild_ErrorCode int32

const (
	LoginFaild_AccountOrPasswardNotMatch LoginFaild_ErrorCode = 0
	LoginFaild_AccIDInvalid              LoginFaild_ErrorCode = 1
	LoginFaild_LoginRepeat               LoginFaild_ErrorCode = 2
	LoginFaild_InnerError                LoginFaild_ErrorCode = 3
)

var LoginFaild_ErrorCode_name = map[int32]string{
	0: "AccountOrPasswardNotMatch",
	1: "AccIDInvalid",
	2: "LoginRepeat",
	3: "InnerError",
}

var LoginFaild_ErrorCode_value = map[string]int32{
	"AccountOrPasswardNotMatch": 0,
	"AccIDInvalid":              1,
	"LoginRepeat":               2,
	"InnerError":                3,
}

func (x LoginFaild_ErrorCode) String() string {
	return proto.EnumName(LoginFaild_ErrorCode_name, int32(x))
}

func (LoginFaild_ErrorCode) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_ae7144eb6e0a1cde, []int{6, 0}
}

type SignUpResponse struct {
	ErrorCode            int32    `protobuf:"varint,1,opt,name=errorCode,proto3" json:"errorCode,omitempty"`
	Version              float32  `protobuf:"fixed32,2,opt,name=version,proto3" json:"version,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *SignUpResponse) Reset()         { *m = SignUpResponse{} }
func (m *SignUpResponse) String() string { return proto.CompactTextString(m) }
func (*SignUpResponse) ProtoMessage()    {}
func (*SignUpResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_ae7144eb6e0a1cde, []int{0}
}

func (m *SignUpResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SignUpResponse.Unmarshal(m, b)
}
func (m *SignUpResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SignUpResponse.Marshal(b, m, deterministic)
}
func (m *SignUpResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SignUpResponse.Merge(m, src)
}
func (m *SignUpResponse) XXX_Size() int {
	return xxx_messageInfo_SignUpResponse.Size(m)
}
func (m *SignUpResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_SignUpResponse.DiscardUnknown(m)
}

var xxx_messageInfo_SignUpResponse proto.InternalMessageInfo

func (m *SignUpResponse) GetErrorCode() int32 {
	if m != nil {
		return m.ErrorCode
	}
	return 0
}

func (m *SignUpResponse) GetVersion() float32 {
	if m != nil {
		return m.Version
	}
	return 0
}

type TosChat struct {
	Name                 string   `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Content              string   `protobuf:"bytes,2,opt,name=content,proto3" json:"content,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *TosChat) Reset()         { *m = TosChat{} }
func (m *TosChat) String() string { return proto.CompactTextString(m) }
func (*TosChat) ProtoMessage()    {}
func (*TosChat) Descriptor() ([]byte, []int) {
	return fileDescriptor_ae7144eb6e0a1cde, []int{1}
}

func (m *TosChat) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_TosChat.Unmarshal(m, b)
}
func (m *TosChat) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_TosChat.Marshal(b, m, deterministic)
}
func (m *TosChat) XXX_Merge(src proto.Message) {
	xxx_messageInfo_TosChat.Merge(m, src)
}
func (m *TosChat) XXX_Size() int {
	return xxx_messageInfo_TosChat.Size(m)
}
func (m *TosChat) XXX_DiscardUnknown() {
	xxx_messageInfo_TosChat.DiscardUnknown(m)
}

var xxx_messageInfo_TosChat proto.InternalMessageInfo

func (m *TosChat) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *TosChat) GetContent() string {
	if m != nil {
		return m.Content
	}
	return ""
}

type TocChat struct {
	Name                 string   `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Content              string   `protobuf:"bytes,2,opt,name=content,proto3" json:"content,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *TocChat) Reset()         { *m = TocChat{} }
func (m *TocChat) String() string { return proto.CompactTextString(m) }
func (*TocChat) ProtoMessage()    {}
func (*TocChat) Descriptor() ([]byte, []int) {
	return fileDescriptor_ae7144eb6e0a1cde, []int{2}
}

func (m *TocChat) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_TocChat.Unmarshal(m, b)
}
func (m *TocChat) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_TocChat.Marshal(b, m, deterministic)
}
func (m *TocChat) XXX_Merge(src proto.Message) {
	xxx_messageInfo_TocChat.Merge(m, src)
}
func (m *TocChat) XXX_Size() int {
	return xxx_messageInfo_TocChat.Size(m)
}
func (m *TocChat) XXX_DiscardUnknown() {
	xxx_messageInfo_TocChat.DiscardUnknown(m)
}

var xxx_messageInfo_TocChat proto.InternalMessageInfo

func (m *TocChat) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *TocChat) GetContent() string {
	if m != nil {
		return m.Content
	}
	return ""
}

type Login struct {
	Account              string   `protobuf:"bytes,1,opt,name=account,proto3" json:"account,omitempty"`
	Passward             string   `protobuf:"bytes,2,opt,name=passward,proto3" json:"passward,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Login) Reset()         { *m = Login{} }
func (m *Login) String() string { return proto.CompactTextString(m) }
func (*Login) ProtoMessage()    {}
func (*Login) Descriptor() ([]byte, []int) {
	return fileDescriptor_ae7144eb6e0a1cde, []int{3}
}

func (m *Login) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Login.Unmarshal(m, b)
}
func (m *Login) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Login.Marshal(b, m, deterministic)
}
func (m *Login) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Login.Merge(m, src)
}
func (m *Login) XXX_Size() int {
	return xxx_messageInfo_Login.Size(m)
}
func (m *Login) XXX_DiscardUnknown() {
	xxx_messageInfo_Login.DiscardUnknown(m)
}

var xxx_messageInfo_Login proto.InternalMessageInfo

func (m *Login) GetAccount() string {
	if m != nil {
		return m.Account
	}
	return ""
}

func (m *Login) GetPassward() string {
	if m != nil {
		return m.Passward
	}
	return ""
}

type PlayerBaseInfo struct {
	PlayerID             uint32   `protobuf:"varint,1,opt,name=PlayerID,proto3" json:"PlayerID,omitempty"`
	Name                 string   `protobuf:"bytes,2,opt,name=Name,proto3" json:"Name,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *PlayerBaseInfo) Reset()         { *m = PlayerBaseInfo{} }
func (m *PlayerBaseInfo) String() string { return proto.CompactTextString(m) }
func (*PlayerBaseInfo) ProtoMessage()    {}
func (*PlayerBaseInfo) Descriptor() ([]byte, []int) {
	return fileDescriptor_ae7144eb6e0a1cde, []int{4}
}

func (m *PlayerBaseInfo) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PlayerBaseInfo.Unmarshal(m, b)
}
func (m *PlayerBaseInfo) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PlayerBaseInfo.Marshal(b, m, deterministic)
}
func (m *PlayerBaseInfo) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PlayerBaseInfo.Merge(m, src)
}
func (m *PlayerBaseInfo) XXX_Size() int {
	return xxx_messageInfo_PlayerBaseInfo.Size(m)
}
func (m *PlayerBaseInfo) XXX_DiscardUnknown() {
	xxx_messageInfo_PlayerBaseInfo.DiscardUnknown(m)
}

var xxx_messageInfo_PlayerBaseInfo proto.InternalMessageInfo

func (m *PlayerBaseInfo) GetPlayerID() uint32 {
	if m != nil {
		return m.PlayerID
	}
	return 0
}

func (m *PlayerBaseInfo) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

type LoginSuccessfull struct {
	PlayerBaseInfo       *PlayerBaseInfo `protobuf:"bytes,1,opt,name=playerBaseInfo,proto3" json:"playerBaseInfo,omitempty"`
	XXX_NoUnkeyedLiteral struct{}        `json:"-"`
	XXX_unrecognized     []byte          `json:"-"`
	XXX_sizecache        int32           `json:"-"`
}

func (m *LoginSuccessfull) Reset()         { *m = LoginSuccessfull{} }
func (m *LoginSuccessfull) String() string { return proto.CompactTextString(m) }
func (*LoginSuccessfull) ProtoMessage()    {}
func (*LoginSuccessfull) Descriptor() ([]byte, []int) {
	return fileDescriptor_ae7144eb6e0a1cde, []int{5}
}

func (m *LoginSuccessfull) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_LoginSuccessfull.Unmarshal(m, b)
}
func (m *LoginSuccessfull) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_LoginSuccessfull.Marshal(b, m, deterministic)
}
func (m *LoginSuccessfull) XXX_Merge(src proto.Message) {
	xxx_messageInfo_LoginSuccessfull.Merge(m, src)
}
func (m *LoginSuccessfull) XXX_Size() int {
	return xxx_messageInfo_LoginSuccessfull.Size(m)
}
func (m *LoginSuccessfull) XXX_DiscardUnknown() {
	xxx_messageInfo_LoginSuccessfull.DiscardUnknown(m)
}

var xxx_messageInfo_LoginSuccessfull proto.InternalMessageInfo

func (m *LoginSuccessfull) GetPlayerBaseInfo() *PlayerBaseInfo {
	if m != nil {
		return m.PlayerBaseInfo
	}
	return nil
}

type LoginFaild struct {
	Code                 LoginFaild_ErrorCode `protobuf:"varint,1,opt,name=code,proto3,enum=msg.LoginFaild_ErrorCode" json:"code,omitempty"`
	XXX_NoUnkeyedLiteral struct{}             `json:"-"`
	XXX_unrecognized     []byte               `json:"-"`
	XXX_sizecache        int32                `json:"-"`
}

func (m *LoginFaild) Reset()         { *m = LoginFaild{} }
func (m *LoginFaild) String() string { return proto.CompactTextString(m) }
func (*LoginFaild) ProtoMessage()    {}
func (*LoginFaild) Descriptor() ([]byte, []int) {
	return fileDescriptor_ae7144eb6e0a1cde, []int{6}
}

func (m *LoginFaild) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_LoginFaild.Unmarshal(m, b)
}
func (m *LoginFaild) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_LoginFaild.Marshal(b, m, deterministic)
}
func (m *LoginFaild) XXX_Merge(src proto.Message) {
	xxx_messageInfo_LoginFaild.Merge(m, src)
}
func (m *LoginFaild) XXX_Size() int {
	return xxx_messageInfo_LoginFaild.Size(m)
}
func (m *LoginFaild) XXX_DiscardUnknown() {
	xxx_messageInfo_LoginFaild.DiscardUnknown(m)
}

var xxx_messageInfo_LoginFaild proto.InternalMessageInfo

func (m *LoginFaild) GetCode() LoginFaild_ErrorCode {
	if m != nil {
		return m.Code
	}
	return LoginFaild_AccountOrPasswardNotMatch
}

func init() {
	proto.RegisterEnum("msg.LoginFaild_ErrorCode", LoginFaild_ErrorCode_name, LoginFaild_ErrorCode_value)
	proto.RegisterType((*SignUpResponse)(nil), "msg.SignUpResponse")
	proto.RegisterType((*TosChat)(nil), "msg.TosChat")
	proto.RegisterType((*TocChat)(nil), "msg.TocChat")
	proto.RegisterType((*Login)(nil), "msg.Login")
	proto.RegisterType((*PlayerBaseInfo)(nil), "msg.PlayerBaseInfo")
	proto.RegisterType((*LoginSuccessfull)(nil), "msg.LoginSuccessfull")
	proto.RegisterType((*LoginFaild)(nil), "msg.LoginFaild")
}

func init() { proto.RegisterFile("src/login.proto", fileDescriptor_ae7144eb6e0a1cde) }

var fileDescriptor_ae7144eb6e0a1cde = []byte{
	// 351 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x9c, 0x92, 0x4f, 0x4f, 0xc2, 0x40,
	0x10, 0xc5, 0x2d, 0x7f, 0xc4, 0x0e, 0x5a, 0x9a, 0xf5, 0x02, 0x46, 0x13, 0xd2, 0x13, 0x17, 0x6b,
	0x82, 0x07, 0x0f, 0xc6, 0x44, 0x04, 0x8d, 0x4d, 0x14, 0xc8, 0xa2, 0x47, 0x0f, 0xeb, 0x76, 0x29,
	0x4d, 0xca, 0x6e, 0xb3, 0xbb, 0x60, 0xfc, 0x2a, 0x7e, 0x5a, 0xb3, 0x5b, 0x0a, 0xc1, 0xa3, 0xb7,
	0x79, 0xd3, 0xf7, 0x7e, 0x9d, 0xe9, 0x14, 0x5a, 0x4a, 0xd2, 0xab, 0x4c, 0x24, 0x29, 0x0f, 0x73,
	0x29, 0xb4, 0x40, 0xd5, 0xa5, 0x4a, 0x82, 0x67, 0xf0, 0x66, 0x69, 0xc2, 0xdf, 0x73, 0xcc, 0x54,
	0x2e, 0xb8, 0x62, 0xe8, 0x1c, 0x5c, 0x26, 0xa5, 0x90, 0x43, 0x11, 0xb3, 0xb6, 0xd3, 0x75, 0x7a,
	0x75, 0xbc, 0x6b, 0xa0, 0x36, 0x34, 0xd6, 0x4c, 0xaa, 0x54, 0xf0, 0x76, 0xa5, 0xeb, 0xf4, 0x2a,
	0xb8, 0x94, 0xc1, 0x0d, 0x34, 0xde, 0x84, 0x1a, 0x2e, 0x88, 0x46, 0x08, 0x6a, 0x9c, 0x2c, 0x8b,
	0xb4, 0x8b, 0x6d, 0x6d, 0x82, 0x54, 0x70, 0xcd, 0xb8, 0xb6, 0x41, 0x17, 0x97, 0xb2, 0x08, 0xd2,
	0x7f, 0x04, 0xef, 0xa0, 0xfe, 0x62, 0xf6, 0x31, 0x16, 0x42, 0xa9, 0x58, 0x71, 0xbd, 0x49, 0x96,
	0x12, 0x9d, 0xc1, 0x51, 0x4e, 0x94, 0xfa, 0x22, 0x32, 0xde, 0xa4, 0xb7, 0x3a, 0xb8, 0x07, 0x6f,
	0x9a, 0x91, 0x6f, 0x26, 0x1f, 0x88, 0x62, 0x11, 0x9f, 0x0b, 0xe3, 0x2e, 0x3a, 0xd1, 0xc8, 0x82,
	0x4e, 0xf0, 0x56, 0x9b, 0xd1, 0xc6, 0x66, 0xb4, 0x82, 0x62, 0xeb, 0x60, 0x02, 0xbe, 0x1d, 0x60,
	0xb6, 0xa2, 0x94, 0x29, 0x35, 0x5f, 0x65, 0x19, 0xba, 0x05, 0x2f, 0xdf, 0xa3, 0x5a, 0x52, 0xb3,
	0x7f, 0x1a, 0x2e, 0x55, 0x12, 0xee, 0xbf, 0x10, 0xff, 0xb1, 0x06, 0x3f, 0x0e, 0x80, 0x25, 0x3e,
	0x91, 0x34, 0x8b, 0xd1, 0x25, 0xd4, 0x68, 0x79, 0x05, 0xaf, 0xdf, 0xb1, 0x84, 0xdd, 0xe3, 0xf0,
	0xb1, 0xbc, 0x0a, 0xb6, 0xb6, 0xe0, 0x03, 0xdc, 0x6d, 0x0b, 0x5d, 0x40, 0x67, 0x50, 0x7c, 0x84,
	0x89, 0x9c, 0x6e, 0x56, 0x1e, 0x0b, 0xfd, 0x4a, 0x34, 0x5d, 0xf8, 0x07, 0xc8, 0x87, 0xe3, 0x01,
	0xa5, 0xd1, 0x28, 0xe2, 0x6b, 0x92, 0xa5, 0xb1, 0xef, 0xa0, 0x16, 0x34, 0x2d, 0x1b, 0xb3, 0x9c,
	0x11, 0xed, 0x57, 0x90, 0x07, 0x10, 0x71, 0xce, 0xa4, 0x65, 0xfa, 0xd5, 0xcf, 0x43, 0xfb, 0xdb,
	0x5c, 0xff, 0x06, 0x00, 0x00, 0xff, 0xff, 0x22, 0x3a, 0x64, 0x7f, 0x49, 0x02, 0x00, 0x00,
}
